
const LOG_SERVER_CONFIGURATION = process.env['LOG_SERVER_CONFIGURATION'] || false;
const LOG_REQUESTS = process.env['LOG_REQUESTS'] || false;

const DEBUG_DELTA_MATCH = process.env['DEBUG_DELTA_MATCH'] || false;
const DEBUG_TRIPLE_MATCHES_SPEC = process.env['DEBUG_TRIPLE_MATCHES_SPEC'] || false;
const DEBUG_DELTA_SEND = process.env['DEBUG_DELTA_SEND'] || false;

const REQUEST_BACKOFF_INITIAL_RETRY_WAIT = process.env['REQUEST_BACKOFF_INITIAL_RETRY_WAIT'] || 50;
const REQUEST_BACKOFF_RATE = process.env['REQUEST_BACKOFF_RATE'] || 1.5;
const REQUEST_BACKOFF_MAX_RETRY_WAIT = process.env['REQUEST_BACKOFF_MAX_RETRY_WAIT'] || 600000; // 6 min

export {
  LOG_SERVER_CONFIGURATION,
  LOG_REQUESTS,
  DEBUG_DELTA_MATCH,
  DEBUG_TRIPLE_MATCHES_SPEC,
  DEBUG_DELTA_SEND,
  REQUEST_BACKOFF_MAX_RETRY_WAIT,
  REQUEST_BACKOFF_RATE,
  REQUEST_BACKOFF_INITIAL_RETRY_WAIT,
};