
const LOG_SERVER_CONFIGURATION = process.env['LOG_SERVER_CONFIGURATION'] || false;
const LOG_REQUESTS = process.env['LOG_REQUESTS'] || false;

const DEBUG_DELTA_MATCH = process.env['DEBUG_DELTA_MATCH'] || false;
const DEBUG_TRIPLE_MATCHES_SPEC = process.env['DEBUG_TRIPLE_MATCHES_SPEC'] || false;
const DEBUG_DELTA_SEND = process.env['DEBUG_DELTA_SEND'] || false;

const REQUEST_INITIAL_RETRY_WAIT = process.env['REQUEST_INITIAL_RETRY_WAIT'] || 100;
const REQUEST_BACKOFF = process.env['REQUEST_BACKOFF'] || 2.0;
const REQUEST_MAX_RETRY = process.env['REQUEST_MAX_RETRY'] || 10000;

export {
  LOG_SERVER_CONFIGURATION,
  LOG_REQUESTS,
  DEBUG_DELTA_MATCH,
  DEBUG_TRIPLE_MATCHES_SPEC,
  DEBUG_DELTA_SEND,
  REQUEST_MAX_RETRY,
  REQUEST_BACKOFF,
  REQUEST_INITIAL_RETRY_WAIT,
};